import { Inter } from "next/font/google";
import "./globals.css";
import { Sidebardesktop } from "@/components/sidebar-desktop";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <Sidebardesktop />
        <main className="ml-64 mt-3">{children}</main>
      </body>
    </html>
  );
}
